name: Generate and Obfuscate Worker Script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build-and-obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Obfuscator
        run: npm install javascript-obfuscator

      - name: Obfuscate from local source file
        run: |
          cat > obfuscate.js << 'EOF'
          const JavaScriptObfuscator = require('javascript-obfuscator');
          const fs = require('fs');
          const path = require('path');
          
          const sourceFileName = '明文源吗';
          const outputFileName = '少年你相信光吗';
          const sourceFilePath = path.join(process.cwd(), sourceFileName);

          if (!fs.existsSync(sourceFilePath)) {
            console.error('错误：在路径 \'' + sourceFilePath + '\' 未找到源文件。请确保您的仓库根目录有名为 \'明文源吗\' 的文件。');
            process.exit(1);
          }

          const originalCode = fs.readFileSync(sourceFilePath, 'utf8');

          if (!originalCode || originalCode.trim().length === 0) {
            console.error('错误：源文件 ' + sourceFileName + ' 为空。');
            process.exit(1);
          }

          // --- 最强混淆配置：无明文内容（性能优化版） ---
          const obfuscationOptions = {
              compact: true,
              // 字符串加密：100%无明文（Base64 + RC4双重编码）
              stringArray: true,
              stringArrayEncoding: ['base64', 'rc4'],
              stringArrayThreshold: 1.0,
              stringArrayRotate: true,
              stringArrayShuffle: true,
              stringArrayWrappersCount: 1,
              stringArrayWrappersChainedCalls: true,
              stringArrayWrappersParametersMaxCount: 2,
              // 变量名/函数名混淆：消除所有标识符明文
              renameGlobals: true,
              identifierNamesGenerator: 'mangled-shuffled',
              // 属性名混淆：消除对象属性明文
              renameProperties: true,
              renamePropertiesMode: 'unsafe',
              // 数字混淆：消除数字明文
              numbersToExpressions: true,
              // 对象键混淆：消除对象键明文
              transformObjectKeys: true,
              // 字符串分割：增强混淆
              splitStrings: true,
              splitStringsChunkLength: 5,
              // 控制流混淆：适度使用保证性能
              controlFlowFlattening: true,
              controlFlowFlatteningThreshold: 0.75,
              // Unicode转义序列
              unicodeEscapeSequence: true,
              // 禁用控制台输出
              disableConsoleOutput: true,
              // 基础配置
              simplify: false,
              target: 'browser'
          };

          const obfuscatedCode = JavaScriptObfuscator.obfuscate(originalCode, obfuscationOptions).getObfuscatedCode();
          
          fs.writeFileSync(path.join(process.cwd(), outputFileName), obfuscatedCode, 'utf8');
          console.log('成功将 \'' + sourceFileName + '\' 混淆并保存至 \'' + outputFileName + '\'。');
          EOF
          node obfuscate.js

      - name: Commit and push the obfuscated file
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add '少年你相信光吗'
          if git diff --staged --quiet; then
            echo "No changes to commit, the obfuscated file is already up-to-date."
          else
            git commit -m "少年你相信光吗"
            git push
          fi
